// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEzTvN7sqlrVBAoBbqzeqAe3xawROlOOE',
    appId: '1:46701113112:web:10c8dbadca5516bc85b86d',
    messagingSenderId: '46701113112',
    projectId: 'eduardo-andrade-firebase-app',
    authDomain: 'eduardo-andrade-firebase-app.firebaseapp.com',
    storageBucket: 'eduardo-andrade-firebase-app.firebasestorage.app',
    measurementId: 'G-DMH77615RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pN_o5GMI2RssAR3m9I0kiKF3XcadYXQ',
    appId: '1:46701113112:android:75ed79dd2adb739c85b86d',
    messagingSenderId: '46701113112',
    projectId: 'eduardo-andrade-firebase-app',
    storageBucket: 'eduardo-andrade-firebase-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLa_xOfKfuNsMTPZFnj0TDV4f2-Q5pqo',
    appId: '1:46701113112:ios:d8ee7de1dc19517385b86d',
    messagingSenderId: '46701113112',
    projectId: 'eduardo-andrade-firebase-app',
    storageBucket: 'eduardo-andrade-firebase-app.firebasestorage.app',
    iosBundleId: 'com.eduardoandrade.trilhaap.trilhaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLa_xOfKfuNsMTPZFnj0TDV4f2-Q5pqo',
    appId: '1:46701113112:ios:d8ee7de1dc19517385b86d',
    messagingSenderId: '46701113112',
    projectId: 'eduardo-andrade-firebase-app',
    storageBucket: 'eduardo-andrade-firebase-app.firebasestorage.app',
    iosBundleId: 'com.eduardoandrade.trilhaap.trilhaap',
  );
}
